modLoader = "javafml"
loaderVersion = "[44,)"
license = "All Rights Reserved"

[[mods]]
modId = "collar_cutting"
version = "1.0-BETA+1.19.3-MC"
displayName = "Collar Cutting"
displayURL="https://www.curseforge.com/minecraft/mc-mods/collar-cutting"
logoFile="logo.png"
credits="Thanks to my Discord server for recommending this mod!"
authors = "LDM"
description = 'A lightweight, configurable mod that allows you to untame wolves (or cut their collars, hence the name) using shears, or any item you want!'

[[dependencies.collar_cutting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="BOTH"
