modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "collar_cutting"
version = "0.1-DEV+1.19.2-MC"
displayName = "Collar Cutting (Untame Wolves)"
#displayURL="http://example.com/" #optional
#logoFile="collar_cutting.png" #optional
credits="Thanks to my Discord server for recommending this mod!"
authors = "LDM"

description = 'A lightweight, configurable mod that allows you to untame wolves using shears!'